sudo:
  - required

os:
  - linux

branches:
  only:
    - master

before_install:
  - sudo add-apt-repository ppa:kelleyk/emacs
  - sudo apt-get update
  - sudo apt-get install emacs25
  - cd src
  - make clean

install:
  - make
