#+STARTUP: indent
#+OPTIONS: ^:{}
#+TITLE: とりあえず八十点を
#+AUTHOR: 岩田 英彬 （入力：中川　恒）
#+LANGUAGE: ja
#+EMAIL: tsunekou1019@gmail.com

一九五二（昭和二八年）年、私は京大法学部の四回生となり、翌年春には卒業を迎えることになった。
当時は秋が就職の時期である。
そのころになっても私は自分がどんな仕事に向いているのか、自らをも把握できないでいた。
慢然と企業の入社試験を受けてみたが、いずれも失敗、そしてどうも普通の会社には向いていない、新聞記者か、学校の先生がいいなと思うようになり、かなり早い段階で、留年を決意した。
そして残る一年で教員免許を取ることにした。

教員免許をもらうには教育実習の他に、教育学関係の学科を教育学部で受講しないといけない。
さらに教養部で人文、社会、自然科学の各系列で十二単位ずつ、計三六単位を得ることが必要であった。

人文、社会科学の単位はあったが、自然科学の方は四単位しかなく、五回生となって、また教養部の授業に通うこととなった。

選択した科目の中には登山で有名な今西錦司先生（当時、理学部の万年講師であった）の自然人類学もあった。
先生の授業はおもしろく、いまでも自然人類学を受講してよかったなと思っている。

またやはり理学部の物理の教授であった田村先生の自然科学史の授業にも出席した（先生の子息の路易”ルイ”君は京都一中で同学年であった）

授業に当り、田村先生は白墨を一本持ってこられるだけである。
本やノートなどは一切持ち込まれることはない。

それでいて、教壇の上を行ったり、来たりして歩きながら、とうとうとよどみなく講義をされる。

科学者の名がでると「これはちょっとスペルがあやしいかも知れませんが」などといいながら、アルファベットで固有名詞を書かれる。
深い知識は驚異であった。

学期末を迎え、テストはやらない、レポートにするとのこと。
学生にとって楽な話であったが、最後に「じつは去年のレポートをまだみていません。諸君のレポートをみるのは来年、再来年あたりになるでしょう」といわれる。

これにはこちらも困った。来春卒業だから教免に必要な単位がそろわらないことになる。
やはり法学部で教免を目指している友人に河田君がいた。
岐阜県の人で、同じ学校で教育実習をやったので、知り合いになったのだ。
この人は下宿して自炊をしていて毎日、自分でつくった弁当を持ってきていた。
好物であったのだろうか。
いつもおかずに金時豆の煮物が入っていたのを覚えている。
温厚篤実といったタイプの人であった。

「教免が取れないと困るから、早くみて下さいと頼みに行こう」
と、二人で田村先生の研究室に行った。

事情を話すと、田村先生は、
「そうですか、それなら君たちのレポートはいずれゆっくり読ましてもらうことにして、とりあえず八十点をあげましょう」と、ほお笑みながら話され、自然科学史の単位はもらえることになった。

研究室を後にして、河田君は「大学に入って以来、八十点なんて点をもらうのは初めてだぞ」といささか感激の体である。
おおらかなリベラリズムの風の一端に触れたよき体験であった。

新制大学で最初の二年間は教養部となり、文科系学生も教養として自然科学の勉強を少しすることになった。
京大では主に理学部の先生が講義に来られたが、理学部の先生方の多くは文科系学生の自然科学などははなから問題にしておられないところがあった。

天文学Ａを担当していた上田先生は単位認定に際し「何でもいいから天文学について四百字詰原稿用紙に一枚書いてこい」とのことで、これには教養部の事務方から「先生、それはあんまりです」との声が出たとか。

田村先生は物理Ａも教えておられたと記憶しているが、相当量の答案を家に持って帰り、奥さんと路易君も手伝って点をつけるのだという伝説があった。

家の二階の階段の上に答案を積み上げ、それを下に落として、一番下に落ちたのから順にいい点をつけて行くのだとのことで、奥さんや路易君にもできるわけだ。
私は物理Ａを選択しなかったが、京都一中から京大に入り、受講していた連中が「答案最後に”ルイ頼む”て書いとこか」と冗談をいって、笑っていた。
